apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-sticky-session.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio-sticky-session.labels" . | nindent 4 }}
    {{- if and .Values.loadBalancing.statefulSessions.enabled (eq .Values.loadBalancing.type "statefulSessions") }}
    {{- if .Values.loadBalancing.statefulSessions.header }}
    istio.io/persistent-session-header: {{ .Values.loadBalancing.statefulSessions.header }}
    {{- else if .Values.loadBalancing.statefulSessions.cookie }}
    istio.io/persistent-session-cookie: {{ .Values.loadBalancing.statefulSessions.cookie }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    {{- include "istio-sticky-session.selectorLabels" . | nindent 4 }}

